export const navbarStyles = {
  container: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
  },
  appBar: {
    position: "static",
    marginBottom: (theme) => theme.spacing(3),
    borderBottom: "1px solid #ccc",
  },
  toolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: (theme) => theme.spacing(1, 2),
    "@media (min-width: 900px)": {
      padding: (theme) => theme.spacing(2, 3),
    },
  },
  toolbarTitle: {
    flexGrow: 1,
  },
  actions: {
    display: "flex",
    alignItems: "center",
  },
  mobileMenuButton: {
    display: { xs: "flex", md: "none" },
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    mt: 1,
    height: "50px",
    mr: -2,
  },
  colorModeToggle: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    ml: 2,
    gap: 0.3,
  },
  colorModeText: {
    fontSize: "0.7rem",
    mt: "-0.3rem",
  },

  mobileMenuItem: {
    display: "flex",
    alignItems: "center",
    gap: 0.4,
    padding: (theme) => theme.spacing(1.4, 2),
    textDecoration: "none",
    color: "inherit",
    textAlign: { xs: "left", sm: "center" },
    "&.active": {
      fontWeight: "bold",
      color: "skyblue",
    },
  },
  mobileMenuIcon: {
    display: "flex",
    alignItems: "center",
    width: "20px",
    height: "20px",
    fontSize: "inherit",
  },
  mobileMenuLabel: {
    ml: 1,
    fontSize: "14px",
  },
  desktopNav: {
    display: "none",
    justifyContent: "flex-end",
    padding: (theme) => theme.spacing(1, 2),
    "@media (min-width: 900px)": {
      display: "flex",
    },
  },
  desktopNavItem: {
    display: "flex",
    alignItems: "center",
    color: "inherit",
    textDecoration: "none",
    marginLeft: (theme) => theme.spacing(2),
    "&.active": {
      fontWeight: "bold",
      color: "skyblue",
    },
  },
  desktopNavIcon: {
    display: "flex",
    alignItems: "center",
    width: "20px",
    height: "20px",
    fontSize: "inherit",
  },
  desktopNavLabel: {
    ml: 1,
    fontSize: "14px",
  },
  content: {
    flexGrow: 1,
    padding: (theme) => theme.spacing(2),
  },

  mobileMenu: {
    display: "flex",
    flexDirection: "column",
    padding: (theme) => theme.spacing(0.1),
    py: "15px",
    position: "absolute",
    top: 74,
    left: 0,
    justifyContent: { sm: "center" },
    width: "100%",
    backgroundColor: (theme) => theme.palette.background.paper,
    boxShadow: 1,
    zIndex: 1301,
    maxHeight: 0,
    opacity: 0,
    transform: "translateY(-10px)",
    overflow: "hidden",
    transition: "max-height 1.0s ease, opacity 0.7s ease, transform 1.0s ease",
    willChange: "max-height, opacity, transform",
    "@media (min-width: 900px)": {
      display: "none",
    },
    "&.open": {
      maxHeight: "400px",
      opacity: 1,
      transform: "translateY(0)",
      overflow: "auto",
    },
  },
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.4)",
    zIndex: 1300,
    opacity: 0,
    visibility: "hidden",
    transition: "opacity 0.3s ease, visibility 0.3s ease",
    "&.visible": {
      opacity: 1,
      visibility: "visible",
    },
  },
};
